### ISSUE TITLE
unclear error markers 

### ISSUE THREAD

**Issue by Dierk** [tricktron/frege-vscode#7]
example from the frege-data-science proje
![Bildschirmfoto 2021-11-24 um 19 55 33](https://user-images.githubusercontent.com/51843/143299030-b587bf4d-94e5-4ac9-bb71-d11f972117d6.png)
ct

**Comment by tricktron** [comment]
Good catch😃.

### Current hypothesis for the error:
The Frege LSP server does not use the `-make` compile flag and does therefore not resolve the dependencies correctly.
